name: Concurrency Example

on:
  workflow_dispatch:

concurrency:
  group: my-workflow
  cancel-in-progress: false

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Start
        run: |
          echo "Workflow started..."
          sleep 60
          echo "Workflow completed."